apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-nginx
  template:
    metadata:
      labels:
        app: kanban-nginx
    spec:
      containers:
      - name: kanban-nginx
        image: kanban:latest
        command: ["nginx", "-g", "daemon off;"]
        imagePullPolicy: Never
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: kanban-nginx-service
spec:
  selector:
    app: kanban-nginx
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
